
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-MenuReviews-Fixtures","number":62,"title":"Angelina menu reviews fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/62"},{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-MenuReviews-team02files","number":61,"title":"added team02 files","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/61"}]
