
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxNjM1Njk1","is_bot":false,"login":"rkirsur","name":"Ritu Kirsur"},"headRefName":"rk-HelpRequest-pagesDebug","number":103,"title":"Rk help request pages debug","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/103"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"git-fix-for-help-request","number":102,"title":"Test PR","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/102"},{"author":{"id":"MDQ6VXNlcjYxNjM1Njk1","is_bot":false,"login":"rkirsur","name":"Ritu Kirsur"},"headRefName":"rk-HelpRequest-pages","number":101,"title":"Rk create, edit, index pages created","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/101"}]
