
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"Kyle-MenuItem-FormComponent","number":70,"title":"UCSBDiningCommonsMenuItemForm component","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/70"},{"author":{"id":"MDQ6VXNlcjYxNjM1Njk1","is_bot":false,"login":"rkirsur","name":"Ritu Kirsur"},"headRefName":"rk-HelpRequest-backend","number":69,"title":"help request backend added","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/69"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"kyle-MenuItem-fixtures","number":68,"title":"Added fixtures for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/68"},{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-MenuReview-Placeholder","number":67,"title":"Angelina menu review placeholder","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/67"},{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-MenuReviews-Table","number":66,"title":"Angelina menu reviews table","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/66"},{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-MenuReviews-Form","number":65,"title":"Angelina menu reviews form","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/65"},{"author":{"id":"U_kgDOBXgO1Q","is_bot":false,"login":"rohankumar2025","name":""},"headRefName":"Rohan-UCSBOrg-backend","number":63,"title":"added backend files from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/63"},{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-MenuReviews-Fixtures","number":62,"title":"Angelina menu reviews fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/62"},{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-MenuReviews-team02files","number":61,"title":"added team02 files","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/61"}]
