
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc0ODAwNTg1","is_bot":false,"login":"AlexLim-Pro","name":"Alex Lim"},"headRefName":"Alex-RecommendationRequest","number":93,"title":"Alex recommendation request","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/93"},{"author":{"id":"U_kgDOBXgO1Q","is_bot":false,"login":"rohankumar2025","name":""},"headRefName":"Rohan-UCSBOrg-Pages","number":91,"title":"Rohan ucsb org pages","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/91"},{"author":{"id":"MDQ6VXNlcjMzMjg5NDM1","is_bot":false,"login":"BK1031","name":"Bharat Kathi"},"headRefName":"Bharat-ArticleTable","number":90,"title":"Bharat article table","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-2/pull/90"}]
